# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: yuhao's maps
email: st40201@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Webjeda Cards is a Bootstrap based jekyll theme for portfolio, photography or any kind of blog.
  
  
  
baseurl: "/slides" # the subpath of your site, e.g. /blog
url: "https://yuhao-kuo.github.io/slides" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
#built-by: yuhao-kuo
copyright:
   name: yuhao.kuo
   link: 'https://yuhao-kuo.github.io'

# Build settings
#markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

include: [_slides]

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

#social
facebook: http://www.facebook.com/yuhao.kuo.tw
quora: 
twitter: http://twitter.com/@yuhao.kuo
github: http://github.com/yuhao-kuo

#facebook like box
#fb-app-id: 549480635219583
#fb-page-url: https://www.facebook.com/webjeda/
#fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

