# Site settings
title: yuhao's map
description: Is yuhao-kuo slides home page.
baseurl: "/slides" # the subpath of your site, e.g. /blog
url: "https://yuhao-kuo.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: yuhao-kuo
user_description: 
email: st40201@gmail.com
twitter_username: yuhao.kuo
github_username:  yuhao-kuo
gplus_username:  
disqus_username: 

# Build settings
#markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /../
  - title: About Me
    url: /../about/
  - title: Blog
    url: /../blog/
  

include: [_slides]

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
